[ISSUE-28] Add package specific documentation
kiegroup/chain-status pull request #34
Opened 2022-08-10 14:34 UTC by lampajr

**Thank you for submitting this pull request**

fix:
- https://github.com/kiegroup/chain-status/issues/28

**referenced Pull Requests**: 
- https://github.com/kiegroup/chain-status/pull/31
- https://github.com/kiegroup/chain-status/pull/34

Add package specific documentation:

- `webpage` documentation which includes specification and usage of its related `generate-app` action.
- `action` documentation which provides the js tool purpose and usage, either from command line or using `generate-data` action.

2022-08-11 15:02 UTC, lampajr commented
I'll promote this as 'ready to review' once https://github.com/kiegroup/chain-status/pull/31 will be merged

2022-11-09 10:36 UTC, Ginxo requested changes
please check

2022-11-09 10:36 UTC, Ginxo commented on packages/webpage/README.md
> +This package contains the source code of React web application.
```suggestion
This package contains the source code of React web application. The web application has to be instantiated by your own configuration like information page markdown file. 
The data consumed by the app is preprocessed by [action package](https://github.com/kiegroup/chain-status/tree/main/packages/action) so no need for a backend and can be easily published on services like Github Packages.
```

2022-11-09 10:36 UTC, Ginxo commented on packages/webpage/README.md
> +## Action Flow
```suggestion
## Installation
```

2022-11-09 10:36 UTC, Ginxo commented on packages/action/README.md
> +This package provides a JS tool which basically consumes information from Github API or Jenkins API and generates a JSON file which is retrieved by the [React web application](https://github.com/kieg
```suggestion
This package provides a NodeJS CLI tool which basically consumes information from Github API and/or Jenkins API and generates a JSON file which is retrieved by the [React web application](https://github.com/kiegroup/chain-status/tree/main/packages/webpage/README.md).
```

2022-11-09 10:36 UTC, Ginxo commented on packages/action/README.md
> +This tool is an easy to use JS tool, in order to use you just need to install all required libraries, build the project and run the automatically generated distribution file at `packages/action/dist/
```suggestion
This tool can be easy use as a NodeJS CLI tool or as a Github Action

### NodeJS CLI Usage

In order to use you just need to install all required libraries, build the project and run the automatically generated distribution file at `packages/action/dist/index.js`.
```

2022-11-09 10:36 UTC, Ginxo commented on packages/action/README.md
> +### Action Flow
```suggestion
### Github Action Flow
```

2022-11-09 11:36 UTC, merged