[ISSUE-33] Generate Github data from projects list
kiegroup/chain-status pull request #35
Opened 2022-08-11 14:59 UTC by lampajr

**Thank you for submitting this pull request**

fix:
- https://github.com/kiegroup/chain-status/issues/33

**referenced Pull Requests**:

Improvements:
- `definition-file` no more strictly required
- Added `projects` input field for actions
- Get Github data from the provided comma-separated list of projects

2022-08-12 09:13 UTC, Ginxo approved these changes
LGTM

2022-08-15 12:29 UTC, shubhbapna requested changes

2022-08-15 12:29 UTC, shubhbapna commented on packages/action/src/bin/github-action.js
> +      : undefined,
```suggestion
    projects: core.getInput("projects")?.split(",")
```
I think we can add optional chaining here given that we are working with node >= 14.0

2022-08-15 12:29 UTC, shubhbapna commented on packages/action/src/lib/github/main.js
> +  var orderedList;
Change `var` to `let`?

2022-08-16 09:49 UTC, lampajr commented
Using the optional chaining, it looks like ncc fails because it is not able to recognize the token.

```
Error: Module parse failed: Unexpected token (8:40)
File was processed with these loaders:
 * ../../node_modules/@zeit/ncc/dist/ncc/loaders/empty-loader.js
 * ../../node_modules/@zeit/ncc/dist/ncc/loaders/relocate-loader.js
 * ../../node_modules/@zeit/ncc/dist/ncc/loaders/shebang-loader.js

You may need an additional loader to handle the result of these loaders.
|   const args = {
|     definitionFile: core.getInput("definition-file"),
>     projects: core.getInput("projects")?.split(","),
|     outputFolderPath: core.getInput("output-folder-path")
```
Still investigating

2022-08-16 11:24 UTC, lampajr commented on packages/action/src/lib/github/main.js
> +  var orderedList;
Changed

2022-08-16 12:15 UTC, shubhbapna commented
I would also go with upgrading ncc from `"@zeit/ncc": "^0.22.3"` to `"@vercel/ncc": "^0.31.1"` especially since `@zeit/ncc` is no longer maintained so we would have probably done the upgrade anyways

2022-08-16 12:16 UTC, shubhbapna approved these changes
LGTM

2022-08-16 12:37 UTC, Ginxo commented
> Using the optional chaining, it looks like ncc fails because it is not able to recognize the token.
> 
> ```
> Error: Module parse failed: Unexpected token (8:40)
> File was processed with these loaders:
>  * ../../node_modules/@zeit/ncc/dist/ncc/loaders/empty-loader.js
>  * ../../node_modules/@zeit/ncc/dist/ncc/loaders/relocate-loader.js
>  * ../../node_modules/@zeit/ncc/dist/ncc/loaders/shebang-loader.js
> 
> You may need an additional loader to handle the result of these loaders.
> |   const args = {
> |     definitionFile: core.getInput("definition-file"),
> >     projects: core.getInput("projects")?.split(","),
> |     outputFolderPath: core.getInput("output-folder-path")
> ```
> 
> It fails running `ncc build --minify src/bin/github-action.js`, if we want to allow optional chaining we would have to upgrade `"@zeit/ncc": "^0.22.3"` to `"@vercel/ncc": "^0.31.1"` (I'd change to `vercel` since the `zeit` one is no more maintained) otherwise we can keep the ternary operator just for now. @Ginxo @shubhbapna wdyt?

please, go ahead with the `@zeit/ncc` replacement

2022-11-09 10:39 UTC, Ginxo requested changes
LGTM, just action patch version should be increased

2022-11-09 11:35 UTC, merged